src/Entity/Pin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\PinRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Pin
{
    /**
     * pour l'utiliser a ne pas oublier l'anotation @ORM\HasLifecycleCallbacks
     */
    use Timestampable;


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="le titre ne peut pas Etre vide")
     * @Assert\Length(min=3)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="la description ne peut pas Etre vide")
     * @Assert\Length(min=10,minMessage="ajouter plus de contenue a la description")
     */
    private $description;

     /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     *  ==>Assert\NotNull(message="Ajouter une image svp")
     * @Assert\Image(maxSize="10M",maxSizeMessage="le fichier est trop grand")
     * @var File|null
     */
    private $imageFile;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ImageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->ImageName;
    }

    public function setImageName(?string $ImageName): self
    {
        $this->ImageName = $ImageName;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable());
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * pour l'utiliser a ne pas oublier l'anotation @ORM\HasLifecycleCallbacks
     */
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName; 
     
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }
    
    public function getFullName(): ?string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image JPG ou PNG',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'Supprimer l\'image',
                'download_label' => 'Telecharger',
                'download_uri' => false,
                'image_uri' => true,
                'asset_helper' => true,
                'imagine_pattern' => 'squared_thumbnail_small'
            ])
            ->add('title')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
            'data_class' => Pin::class
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PinsController extends AbstractController
{

    private $em;

    public function __construct(EntityManagerInterface $em){
        $this->em = $em;
    }


    #[Route('/', name: 'app_home', methods:"GET")]
    public function index(PinRepository $pr): Response
    {

        $pins = $pr->findBy([],['createdAt' => 'DESC']);


        return $this->render('pins/index.html.twig', [
            'pins' => $pins
        ]);
    }


    /**
     * @Route("/pins/{id<[0-9]+>}",name="app_pins_show")
     */
    public function show(Pin $pin):Response{
        return $this->render('pins/show.html.twig',['pin' => $pin]);
    } 

    


    #[Route('/pins/create', name: 'app_pins_create',methods:["GET","POST"])]
    public function create(Request $req, UserRepository $userRepo):Response{

        $pin = new Pin;

        $form = $this->createForm(PinType::class,$pin);

        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $pabios = $userRepo->findOneBy(['id' => 1]);
            $pin->setUser($pabios);
            $this->em->persist($pin);
            $this->em->flush();

            $this->addFlash('success','l\'article a été ajouté avec succès');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('pins/create.html.twig',[
            'form' => $form->createView()
        ]);
    }

     /**
     * @Route("/pins/{id<[0-9]+>}/edit",name="app_pins_edit",methods={"GET","POST"})
     */
    public function edit( Request $req,Pin $pin):Response{
        // prochaine etape changer le POST EN PUT 
        $form = $this->createForm(PinType::class,$pin);
        
        
        $form->handleRequest($req);

            if($form->isSubmitted() && $form->isValid()){
                 
                $this->em->flush();

            $this->addFlash('success','l\'article a été modifier  avec succès');

    
                return $this->redirectToRoute('app_home');
            }

        return $this->render('pins/edit.html.twig',[
            'pin' => $pin,
            'form' => $form->createView()
        ]);
    } 
    
     /**
     * @Route("/pins/{id<[0-9]+>}/delete",name="app_pins_delete",methods={"GET","POST"})
     */
    public function delete( Request $req,Pin $pin):Response{
         // boeug sur l'annotation methods="DELETE" a revoir

        //supprime si le token envoyer par l'utiisateur est valide 
        if($this->isCsrfTokenValid('pin_deletion_'.$pin->getId(),$req->request->get('csrf_token'))){
             $this->em->remove($pin);
            $this->em->flush();

            $this->addFlash('info','l\'article a été supprimer avec succès');

        }
       

        return $this->redirectToRoute('app_home');
 
    }
}

templates/pins/_form.html.twig
{{form_start(form)}}
        {{form_widget(form)}}
        <input type="submit"  class="btn btn-primary btn-block" value="{{ submitButtonText }} " formnovalidate>
{{form_end(form)}}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}New Pin{% endblock %}

{% block body %}
 

<div class="row">
    <div class="col-md-6 mx-auto">
        <h1> Ajouter un Article</h1>
        {{ include('pins/_form.html.twig',{submitButtonText: 'Create'} )   }}
         
    </div>
   
</div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}


{% block title  'Edit Pin' ~ pin.id %} 

{% block body %}
 

<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>Modifier l'Article #{{ pin.id }}</h1>
        {{ include('pins/_form.html.twig',{submitButtonText: 'Update'} )   }}
         
    </div>
   
</div>
{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}


{% block title %}All pins{% endblock %}

{% block body %}
 {% if pins|length > 0 %}

   <div class="container">
      <h1 class="mb-4 text-center"> {{ pluralize(pins|length,'Article') }}   </h1>
      {% for row in pins|batch(3) %}
      <div class=" mb-5 row">
         {% for pin in row %}
         <div class="col-md-4">
            <article class="pin bg-white rounded shadow"  >
               <div class="mw-100 overflow-hidden">
                  <a   href="{{ path('app_pins_show',{id: pin.id}) }}">
                     <img class="w-100 rounded-top" src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('images/profils.jpeg') )  | imagine_filter('squared_thumbnail_medium')}}" alt="{{ pin.title }}">
                     
                  </a>
               </div>
               
               <a class=" h5 pt-4 text-primary text-muted text-decoration-none" href="{{ path('app_pins_show',{id: pin.id}) }}"> <h2>{{ pin.title }}</h2> </a>
               <p>{{ pin.description|u.truncate(10, '...', false) }}</p>
               <p>Publié Par {{ pin.user.fullName }}  le {{ pin.createdAt|date("d/m/Y")  }}  </p>
            </article>
         </div>
         {% endfor %}
      </div>
      {% endfor %}
   </div>

   {% else %}
      <p class="h1 mt-5 text-center">Aucun Article !  <a href="{{ path('app_pins_create')}}">Rediger le votre</a> </p>
   {% endif %}
      
{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}


{% block title pin.title %}  

{% block body %}

<div class="jumbotron p-3 p-md-5 text-white rounded bg-primary">
    
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic"> {{ pin.title }}</h1>
      <p class="lead my-3">Publié Par {{ pin.user.fullName }} le {{ pin.createdAt|date("d/m/Y")  }}  </p>

    </div>
  </div>

<div class="container mt-4">
   <div class="row">
      <div class="col-2 "> 
          
         <img class="w-100 rounded-top" src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('images/profils.jpeg') )  | imagine_filter('squared_thumbnail_medium')}}" alt="{{ pin.title }}">
         
         
         
      </div>
      <div class="col">
       <p>{{ pin.description }}</p>
      </div>
   </div>
   
</div>


<a class="btn btn-info" href="{{ path('app_pins_edit',{id:pin.id} )}}"> Edit </a>
<a class="btn btn-info" href="#" onclick="event.preventDefault; confirm('Etes vous sûr de vouloir supprimer') && document.getElementById('js_pin-delete').submit();"> Delete </a>

<form id="js_pin-delete" action="{{ path('app_pins_delete',{id:pin.id} )}}" method="POST" style="display: none;">
    <input   type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id)}}">
    <input   type="hidden" name="_method" value="DELETE">
</form>



{% endblock %}